modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "tiabfix"
version = "1.0.0"
displayName = "TIAB Entity Fix"
description = '''Fixes the Time in a Bottle stacked block acceleration issue.'''
authors = "zulu"

[[mixins]]
config = "tiabfix.mixins.json"

[[dependencies.tiabfix]]
modId = "tiab"
type = "required"
versionRange = "[6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tiabfix]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tiabfix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
